/eda/home/dlamana/tfm/rtl/pe/sauria/adder/adder_gear_2c.sv
/eda/home/dlamana/tfm/rtl/pe/sauria/adder/adder_gear.sv
/eda/home/dlamana/tfm/rtl/pe/sauria/adder/adder_generic.sv
/eda/home/dlamana/tfm/rtl/pe/sauria/adder/adder_ideal.sv
/eda/home/dlamana/tfm/rtl/pe/sauria/adder/adder_loa.sv
/eda/home/dlamana/tfm/rtl/pe/sauria/adder/adder_truah.sv
/eda/home/dlamana/tfm/rtl/pe/sauria/adder/adder_trua.sv
/eda/home/dlamana/tfm/rtl/pe/sauria/multiplier/bam_cell.sv
/eda/home/dlamana/tfm/rtl/pe/sauria/multiplier/lopd.sv
/eda/home/dlamana/tfm/rtl/pe/sauria/multiplier/mul_2x2.sv
/eda/home/dlamana/tfm/rtl/pe/sauria/multiplier/multiplier_bam.sv
/eda/home/dlamana/tfm/rtl/pe/sauria/multiplier/multiplier_booth.sv
/eda/home/dlamana/tfm/rtl/pe/sauria/multiplier/multiplier_generic.sv
/eda/home/dlamana/tfm/rtl/pe/sauria/multiplier/multiplier_ideal.sv
/eda/home/dlamana/tfm/rtl/pe/sauria/multiplier/multiplier_log.sv
/eda/home/dlamana/tfm/rtl/pe/sauria/multiplier/multiplier_wallace.sv
/eda/home/dlamana/tfm/rtl/pe/sauria/multiplier/wallace_16.sv
/eda/home/dlamana/tfm/rtl/pe/sauria/multiplier/wallace_4.sv
/eda/home/dlamana/tfm/rtl/pe/sauria/multiplier/wallace_8.sv
/eda/home/dlamana/tfm/rtl/pe/sauria/sa_processing_element.sv
/eda/home/dlamana/tfm/rtl/pe/sauria/zero_det_neg.sv
